// ============================================================================
// OPPORTUNITY  (keep ALL columns; add helper flags only)
// ============================================================================
let
    // ------------------------------------------------------------------------
    // SOURCE  (point at your existing initial step for Opportunity)
    // ------------------------------------------------------------------------
    Opportunity_source = #"Opportunity_source",
    #"Removed Columns" = Table.RemoveColumns(Opportunity_source,{"IsDeleted", "Amount", "Probability", "ExpectedRevenue", "IsWon", "ForecastCategory", "ForecastCategoryName", "HasOpportunityLineItem", "Pricebook2Id", "FiscalQuarter", "FiscalYear", "Fiscal", "ContractId", "HasOpenActivity", "HasOverdueTask", "ActivityMetricId", "Budget_Confirmed__c", "Discovery_Completed__c", "ROI_Analysis_Completed__c", "Win_Loss_Reason__c", "Grouped_Probability__c", "SFDC_TEST__c", "Sales_Rep__c", "Pricing_Model__c", "Time_of_Close__c", "WOW_Report_on__c", "WOW_Category__c", "WOW_Comment__c", "Deal_Team_Stage__c", "Channel_Partner_Sales_Status__c", "Channel_Partner_Report_Comments__c", "Implementation_Fee__c", "Projected_Start_Date__c", "Lost_to_Competitor__c", "DNBI__CommercialCreditScore__c", "NRO_Study_Annual_Spend__c", "DNBI__Commercial_Credit_Score_Class__c", "NRO_Study_Net_Revenue__c", "NRO_Study_Net_Revenue_Percent__c", "NRO_Annual_Shipments__c", "NRO_Annual_Spend_Dollars__c", "NRO_Procurement_Savings_Dollars__c", "NRO_Procurement_Net_Revenue_Dollars__c", "NRO_Procurement_Net_Revenue_Percent__c", "Owner_Commission_YR1__c", "Annual_Net_Revenue_Dollars__c", "Annual_Net_Revenue_Percent__c", "Custom_User__c", "ZOHO_Project_ID__c", "ZOHO_Owner_Name__c", "Deal_Team_Comments__c", "LastActivityDate", "ContactId", "LastViewedDate", "LastReferencedDate", "SyncedQuoteId", "Terminated__c", "Termination_Date__c", "Termination_Reason__c", "LOA_Signor_Name__c", "LOA_Signor_Title__c", "LOA_SOW_Contact_Name_ID__c", "LOA_Contact_Phone__c", "LOA_DAte__c", "Update_Me__c", "DB_Competitor__c", "Owner_2_Commission_YR1__c", "Multi_Modal_Team_Member__c", "Commission_Verified_Send_Email__c", "Top_10_Opportunity__c", "Channel_Partner_Commission_YR1__c", "Manager_Name__c", "Owner_Commission_Mths_13_to_36__c", "Owner_Commission_Mth_37_Plus__c", "Owner_2_Commission_Mths_13_to_36__c", "Owner_2_Commission_Mth_37_Plus__c", "EGI_Opportunity_ID__c", "Closed_Reason__c", "Channel_Partner_Commission_YR2__c", "Channel_Partner_Commission_YR3__c", "Market__c", "Channel_Partner_Name__c", "Multi_Modal_Split__c", "Opportunity_Source__c", "Owner_2_Name__c", "Reference_Contact__c", "Closed_Details__c", "Registered_with_OPN__c", "Deal_Review_and_Product__c", "FUM__c", "Opportunity_Rank__c", "Software_Module__c", "Commission_Completion__c", "KS_Product__c", "Cross_Sell__c", "Cross_Sell_Reference__c", "Duration_Weeks__c", "MX_Program_Source__c", "Week__c", "DashboardsGSP__Amount_Won__c", "DashboardsGSP__Close_Date_Extensions__c", "DashboardsGSP__Close_Date_Month_Extensions__c", "DashboardsGSP__Date_Opportunity_was_Closed__c", "DashboardsGSP__Days_Open_Delete__c", "DashboardsGSP__Days_Open__c", "DashboardsGSP__Days_Since_Last_Stage_Change__c", "DashboardsGSP__Last_Stage_Change_Date__c", "GSP_LeadDash__Amount_Won__c", "GSP_LeadDash__From_Converted_Lead__c", "Generate_Revenue_Date__c", "PushCount__c", "Push_Counter__c", "Cross_Sell_Source__c", "Reports_To__c", "Outlook__c", "Commercialization__c", "DNBI__Commercial_Credit_Score_Percentiles__c", "DNBI__D_B_Address__c", "DNBI__D_B_Avg_High_Credit__c", "DNBI__D_B_City__c", "DNBI__D_B_Country__c", "DNBI__D_B_High_Credit__c", "DNBI__D_B_State_Province__c", "DNBI__D_B_Zip_Postal_Code__c", "DNBI__DnB_Application_Created_Date__c", "DNBI__DnB_Application_ID__c", "DNBI__DnB_Application_Modified_Date__c", "DNBI__DnB_Company_Name__c", "DNBI__DnB_Credit_Limit__c", "DNBI__DnB_Credit_Term_Status__c", "DNBI__DnB_DUNS_NO__c", "DNBI__DnB_Early_Payment_Discount__c", "DNBI__DnB_Payment_Terms__c", "DNBI__DnB_Requested_Amount__c", "DNBI__DnB_Status__c", "DNBI__Employees__c", "DNBI__Financial_Stress_Score_Class__c", "DNBI__Financial_Stress_Score_Percentile__c", "DNBI__Financial_Stress_Score__c", "DNBI__OppCountry__c", "DNBI__OppState__c", "DNBI__PAYDEX__c", "DNBI__Primary_NAICS__c", "DNBI__Primary_SIC__c", "DNBI__Rating__c", "DNBI__Viability_Company_Profile__c", "DNBI__Viability_Data_Depth_Indicator__c", "DNBI__Viability_Portfolio_Comparison__c", "DNBI__Viability_Rating__c", "DNBI__Viability_Viability_Score__c", "DNBI__Years_in_Business__c", "DFB_Connection__c", "CP_Technology_Company_Source__c", "Reseller__c", "Partnership_Referral__c", "Partnership_Reseller__c", "Redwood_Connects_Calc_for_Spinify__c", "Win_Summary__c", "Cross_Sales_Path__c", "Parcel_Reference__c", "Oracle_Package__c", "SaaS_Partner_Referral__c", "Submitted_Date__c", "Anticipated_Volume__c", "Pricing_Analyst__c", "Shared_ISA__c", "Opportunity_Owner_3__c", "Opportunity_Type__c", "Time_Duration__c", "Project_ID__c", "Brokerage_Opportunity__c", "Backhaul_lanes__c", "Identified_focus_lanes__c", "LoadRunner_Customer_Number__c", "Previous_Load_History__c", "RFP_Due_Date__c", "Source_System__c", "of_Bid_Rounds__c", "Rate_Expiration_Date__c", "Rate_Effective_Date__c", "Expected_Feedback_Date__c", "Sourcing_Allowed_To_Contact_Incumbents__c", "Trailer_Requirements__c", "Competition_Intel__c", "Equipment_Type__c", "Seasonality_of_Business__c", "Fuel_Surcharge_To_Use__c", "Commodity_ies_Shipping__c", "Identified_Focus_Lanes_Min_No_Margin__c", "Additional_Information_Strategy__c", "Competition_Details__c", "Channel_Partner_Segment__c", "Channel_Lead_Source__c", "Hub_Leader__c", "Bill_To_Completed__c", "Requested_Credit__c", "Email_Group_Created__c", "LR_User_Group_Created__c", "Contract_Reviewed__c", "Bid_Documents_Reviewed__c", "EDI_Requirements__c", "Tracking_Requirements__c", "Known_KPI_s__c", "Rep_Forecast__c", "Manager_Forecast__c", "Manager_Amount__c", "Rep_Probability__c", "Cross_Sell_User_Source__c", "Channel_Type__c", "SDR_Service_Line__c", "Estimated_Contract_Value__c", "GCLID__c", "utm_keyword__c", "Onboarding_Effort__c", "RPS_Onboarding_Team__c", "Non_Standard_Scenario__c", "Marketing_Contribution__c", "Referring_Employee__c", "Marketing_Lead_Notes_Opp__c", "Marketing_Campaign_Notes_Opportunity__c", "Media_Partner_Opportunity__c", "Pardot_Comments__c", "Solution_Profile__c", "Actual_Close_Date__c", "Lead_Source_Name_Opportunity__c", "Lead_Source_Type_Opportunity__c", "Company_Segmentation__c", "LTL_Spend__c", "TL_Spend__c", "Parcel_Spend__c", "Did_you_verify_LTL_spend__c", "Did_you_verify_TL_spend__c", "Did_you_verify_Parcel_spend__c", "Accessorial__c", "Budget__c", "Competitor_Name_s__c", "FSC__c", "Automation_Date_Time__c", "Last_Activity_Date_CUSTOM__c", "Next_Activity_Date__c", "Other_TMS__c", "Prospect_Pain_Points__c", "Round_1_Due_Date__c", "Round_2_Due_Date__c", "Round_3_Due_Date__c", "Anticipated_Actual_Rev__c", "Has_Contact_Rol__c", "Is_this_an_RFP__c", "Playbook__c", "Is_Automation_Bypassed__c", "Cross_Sale_Path__c", "High_Value_Cargo_Insurance_Required__c", "Likleyhood_to_Win__c", "RFP_Ranking__c", "Channel_Partner_Lookup__c", "Channel_Partner_Influence__c", "Influencing_Partner__c", "Did_you_upload_RFP_docs__c", "Procurement_Strategy__c", "Rate_Type__c", "Equipment_Type_Details__c", "Fuel_Surcharge__c", "Opportunity_Go_Live_Date__c", "Related_Channel_Partner__c", "Support_Request__c", "Communication_Support__c", "Meeting_Support__c", "Internal_Champion_Support__c", "Primary_Campaign__c", "Opportunity_Influences__c", "SDR_Opp_Prospecting_Date_del__c", "Customer_Onboarding_checkbox__c", "Customer_Onboarding_Flow__c", "Customer_Onboarding_Name_Text__c", "Partner_Influence_Lookup__c", "Contract_Name__c", "Contract_Organization__c", "Contract_URL__c", "Contract_Status__c", "Contract_Sub_Status__c", "Contract_ID_IntelAgree__c", "Contract_Error_Message__c", "Contract_Comments__c", "Contract_Tempalte__c", "Contract_Organizations__c", "SDR_Opp_Prospecting_Date__c", "Qualified_Date__c", "Define_Solution_Date__c", "Selection_Date__c", "Contract_Date__c", "Generating_Revenue_DateStamp__c", "Closed_Won_Date__c", "Closed_Lost_Date__c", "Special_Requirements_on_any_RFP_Lanes__c", "Cargo_Insurance_Amount__c", "Channel_Cadence__c", "X4PL_Opportunity__c", "Originator_Only__c", "Last_Activity_120__c", "Last_Activity_90_Days__c", "Brokerage_Growth_Type__c", "Booked_ASP__c", "Solution_Sales__c", "Win_Review_Status__c", "Is_there_a_Competitor__c", "SE_Active__c", "SE_Phase__c", "CS_Churn_Reason__c", "In_Manager_Call__c", "Type_of__c", "Opportunity_Owner_same_as_CreatedbyID__c", "Tactical_Customer__c", "Current_Customer__c", "New_Customer__c", "X4PL_Generated__c", "Known_Competitor__c", "Created_Date_90_days__c", "Days_in_SDR_Prospecting_Stage__c", "First_Time_Qualified__c", "Enterprise_Deal__c", "Days_in_Qualified_Stage__c", "Days_in_Define_Solution_Stage__c", "Days_in_Selection_Stage__c", "Days_in_Contract_Stage__c", "Expected_Annual_Freight_Volume__c", "Sales_Lead_Mexico__c", "Sales_Lead_USA__c", "Times_Discovery_Meetings__c", "Touchpoints_Support__c", "Outcomes_Support__c", "Additional_Info_Support__c", "CapEvents_Notes__c", "Opp_Originator__c", "Cumulative_Days_in_SDR_Prospecting__c", "Cumulative_Days_in_Qualified_Stage__c", "Cumulative_Days_in_Define_Solution_Stage__c", "Cumulative_Days_in_Selection_Stage__c", "Cumulative_Days_in__c", "Service_Line_Mx_Opp__c", "Type_of_freight__c", "Transactional_Growth_Type__c", "Contract_Growth_Type__c", "Number_of_Competitors__c", "Did_you_upload_the_FSC_schedule__c", "Did_you_upload_the_accessorial_list__c", "Customer_or_Redwood_Accesorial__c", "Direct_Feedback_Champion__c", "Trailer_Requirements_Multi__c", "Expected_Customer_Savings__c", "How_does_the_customer_plan_to_award__c", "Spot_Loads_Available_to_Redwood__c", "Limited_amount_of_drop_trailer_lanes__c", "Customer_Peak_Surges__c", "Previous_Contract_Volume__c", "Previous_Contract_NR__c", "Total_RFP_Volume__c", "Total_Submitted_Volume__c", "Total_RFP_Lane_Count__c", "Total_Volume_Won__c", "Total_Lane_Count_Won__c", "Expected_NR_LD__c", "Estimated_NR__c", "Focus_Lanes_Submitted__c", "Focus_Lanes_Won__c", "Total_Lane_Count_Submitted__c", "How_does_customer_evaluate_submission__c", "How_do_brokers_fit_into_their_strategy__c", "Other_Pain_Points__c", "Other_Discovery_Information__c", "What_is_their_spot_strategy__c", "Additional_RFP_Timing_Comments__c", "Tactical_or_Strategical_Customer__c", "Geography__c", "Northbound__c", "Southbound__c", "Mexico_Transportation_Type__c", "Available_Gross_Revenue__c", "Available_Number_of_Loads__c", "Available_Number_of_Lanes__c", "Days_Qualified_to_Closed__c", "Calculated_Opportunity_Score__c", "Discovery_Assessment_Submitted__c", "Valid_Contact_Roles__c", "Cross_Sale__c", "Business_Awarded__c", "Team__c", "AEA_Year_2__c", "AEA_Year_3__c", "Access_to_Decision_Maker__c", "Key_Upcoming_Events__c", "Deal_Risks__c", "Evaluation_Criteria__c", "Action_Plan__c", "Support_Needed__c", "Executive_Sponsor_Actions__c", "Competitor_Differentiation__c", "Onsite_Meeting__c", "Commercial_Services_Intake__c", "Related_Products_Count__c", "Last_Meeting_Date__c", "Closed_Opportunity_Score__c", "Cross_Border_Product__c", "SDR_Suggested_Solution__c", "Brokerage_Top_Opportunity__c", "Original_Opportunity__c", "Auto_Renewal_Clause__c", "Auto_Renewal_Deadline__c", "Carrier_EDI_Integrations_Contracted__c", "Carrier_EDI_Integrations_Current__c", "Transactions_Contracted_per_year__c", "Transactions_Used_Last_12_Months__c", "FUM_Contracted_in_Platform_Millions__c", "FUM_in_Platform_Last_12Months_Millions__c", "Customer_Connections_Contracted__c", "Customer_Connections_Current__c", "Auto_Renewed_for_New_Term__c", "Beneficial_Cargo_Owner_BCO__c", "Transload_or_Direct_Service__c", "Expected_Net_Revenue__c", "Mx_Pricing_Status__c", "Block_Bracing_Equipment__c", "Mx_Trailer_Requirements__c", "Mx_Cargo_Value__c", "Mx_Fuel_Surcharge__c", "Mx_Special_Requirements__c", "Mx_Commodities_Shipping__c", "Mx_Monthly_Volume__c", "Customer_New_to_Channel_Partner__c", "Oracle_Products_In_Opp__c", "Other_Comments__c", "RFP_Email_Date__c", "Onsite_Meeting_Last_6_Months__c", "Pricing_Team__c", "Type_of_Discovery_Completed__c", "Mx_Opportunity_Details__c", "Hazmat_UN_Number__c", "Temperature_Range__c", "Hazmat_Requirement__c", "Temp_Controlled_Required__c", "Type_of_Freight_Mx__c", "Crossing_Point_Border__c", "Mx_Pricing_Notes__c", "Customer_registered_with_a_customs_broke__c", "Minimum_Lane_Count_Volume_to_be_Onboard__c", "SDR_Campaign_Category__c", "Mx_Pricing_Rep__c", "Other_Competitor__c", "LeadSource"}),
    // ------------------------------------------------------------------------
    // FILTER: EDI Carrier Integration scope (preserve all columns)
    // ------------------------------------------------------------------------
    #"Filtered EDI" =
        Table.SelectRows(#"Removed Columns", each ([Opportunity_Record_Type_Formula__c] = "EDI Carrier Integration")),
    #"Filtered Rows" = Table.SelectRows(#"Filtered EDI", each ([CloseDate] <> #date(2020, 1, 1))),

    // ------------------------------------------------------------------------
    // TYPES for a few key fields (we do NOT drop any columns)
    // ------------------------------------------------------------------------
    #"Typed (key fields only)" =
        Table.TransformColumnTypes(
            #"Filtered Rows",
            {
              {"CreatedDate", type datetime},
              {"CloseDate", type date},
              {"Intake_Form_Received_Date__c", type date},
              {"Actual_Deployment_Go_Live_Date__c", type nullable date}
            },
            "en-US"
        ),

    // ------------------------------------------------------------------------
    // FLAGS (non-destructive; keep all original cols)
    //  - IsRunMaintain: Name contains any Run&Maintain variant
    //  - IsEDIOnboardingEligible: in-scope EDI AND not Run&Maintain
    // ------------------------------------------------------------------------
    Add_IsRunMaintain =
        Table.AddColumn(
            #"Typed (key fields only)", "IsRunMaintain",
            each let nm = Text.Upper(Text.From(Record.FieldOrDefault(_, "Name", ""))) in
                 Text.Contains(nm,"RUN&MAINTAIN")
              or Text.Contains(nm,"RUN& MAINTAIN")   
              or Text.Contains(nm,"RUN & MAINTAIN")
              or Text.Contains(nm,"RUN/MAINTAIN")
              or Text.Contains(nm,"RUN AND MAINTAIN"),
            type logical
        ),

    // ------------------------------------------------------------------------
    // CloseDate normalization (treat 12/31/2099 as placeholder → null)
    // ------------------------------------------------------------------------
    Add_CloseDate_Normalized =
        Table.AddColumn(
            Add_IsRunMaintain, "CloseDate_Normalized",
            each if [CloseDate] = #date(2099,12,31) then null else [CloseDate],
            type nullable date
        ),
    Add_IsHardGoLive = Table.AddColumn(Add_CloseDate_Normalized, "IsHardGoLive", each if [Hard_Go_Live_Date__c]=null then false else true),
    Add_HardGoLive = Table.AddColumn(Add_IsHardGoLive, "HardGoLive", each if [Hard_Go_Live_Date__c]=null then "HardGoLive" else "Ad-Hoc"),
    Rename_RPS_to_Innovate = Table.ReplaceValue(Add_HardGoLive,"Innovate Group (formerly RPS)","Innovate",Replacer.ReplaceText,{"Business_Unit__c"}),    
    Rename_Column_TMS = Table.RenameColumns(Rename_RPS_to_Innovate,{{"System_Setup__c", "TMS"}}),
    Rename_Column_Company = Table.RenameColumns(Rename_Column_TMS,{{"Primary_Campaign_Name__c", "Customer"}}),
    Rename_Westlake_to_FAST = Table.ReplaceValue(Rename_Column_Company,"WestLake","FAST/Simplified",Replacer.ReplaceText,{"TMS"})
in
    Rename_Westlake_to_FAST